git:
  depth: 1
language: node_js
node_js:
  - '0.12'
install:
  - npm install
  - jspm install
script:
  - npm run build
  - if [ "${TRAVIS_TAG}" != "" ]; then zip systemjs-reloader.zip systemjs-reloader.js systemjs-reloader.js.map; fi
cache:
  directories:
  - node_modules
  - jspm_packages
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "${GITHUB_AUTH_TOKEN}"
  file: "systemjs-reloader.zip"
  on:
    tags: true