git:
  depth: 1
language: node_js
node_js:
  - '0.11'

before_install:
  - npm install
  - '[ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] && jspm config registries.github.auth ${GITHUB_AUTH} || false'
  - jspm install
script:
  - npm run test-format
  - npm run test
  - npm run build
cache:
  directories:
  - node_modules
  - jspm_packages